# Generated by Django 3.1.5 on 2021-02-08 07:22

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(default=blog.models.gen_key, primary_key=True, serialize=False),
        ),
    ]
