# Generated by Django 3.1.5 on 2021-02-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210227_1014'),
        ('blog', '0003_auto_20210215_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liker',
            field=models.ManyToManyField(related_name='liked_posts', to='user.Profile'),
        ),
    ]
