# Generated by Django 3.1.5 on 2021-04-08 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_liker'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='original_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
    ]
