# Generated by Django 3.1.5 on 2021-02-04 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20210203_0727'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
