# Generated by Django 3.1.5 on 2021-04-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210329_0723'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='liker',
            field=models.ManyToManyField(related_name='liked_messages', to='user.Profile'),
        ),
    ]
