# Generated by Django 3.1.5 on 2021-02-08 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(default=user.models.gen_key, primary_key=True, serialize=False)),
                ('created_at_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('handle', models.TextField(default=user.models.gen_hex, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('profile_image', models.ImageField(default='default_profile.png', upload_to='profile_pics')),
                ('background_image', models.ImageField(default='default_background.png', upload_to='background_pics')),
                ('bio', models.TextField(blank=True, max_length=160)),
                ('location', models.TextField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
