# Generated by Django 3.1.5 on 2021-04-15 07:29

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210329_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(default=user.models.gen_key, primary_key=True, serialize=False),
        ),
    ]
